name: 'action-gitcode-release'
description: '在GitCode项目发布release(可以上传附件)'
inputs:
  gitcode_action:
    description: '执行的操作类型: create_release, upload_asset, delete_release, delete_asset, update_asset'
    required: true

  gitcode_owner:
    description: 'GitCode 用户名, 项目URL中可获取'
    required: true
  gitcode_repo:
    description: 'GitCode 项目名, 项目URL中可获取'
    required: true
  gitcode_token:
    description: 'GitCode api token'
    required: true
    
  gitcode_tag_name:
    description: 'GitCode Tag 名称, 提倡以v字母为前缀做为Release名称，例如v1.0或者v2.3.4'
    required: false
  gitcode_release_name:
    description: 'GitCode release 名称'
    required: false
  gitcode_release_body:
    description: 'GitCode release 描述'
    required: false
  gitcode_target_commitish:
    description: 'GitCode 分支名称或者commit SHA'
    required: false

  gitcode_files:
    description: '上传的附件列表(多个文件)'
    required: false
    
  gitcode_file_name:
    description: '上传的附件名称(单个文件)'
    required: false
  gitcode_file_path:
    description: '上传的附件的本地路径(单个文件)'
    required: false
    
  gitcode_release_id:
    description: '指定的release ID (upload_asset操作时可选，优先级高于tag_name)'
    required: false
    
  gitcode_upload_retry_times:
    description: '上传附件失败后的尝试次数'
    required: false

  gitcode_delete_asset:
    description: '要删除的单个附件名称 (delete_asset操作时使用)'
    required: false
  gitcode_delete_assets:
    description: '要删除的多个附件名称，每行一个文件名 (delete_asset操作时使用)'
    required: false
    
  gitcode_old_asset_name:
    description: '要更新的旧附件名称 (update_asset操作时使用)'
    required: false
  gitcode_new_file_path:
    description: '新附件的本地路径 (update_asset操作时使用)'
    required: false
    
outputs:
  release-id:
    description: '创建的release的id'
    value: ${{ steps.release.outputs.release-id }}
  download-url:
    description: '附件的下载地址'
    value: ${{ steps.release.outputs.download-url }}
runs:
  using: "composite"
  steps:
    - name: Execute GitCode Release Action
      id: release
      shell: bash
      env:
        gitcode_action: ${{ inputs.gitcode_action }}
        gitcode_owner: ${{ inputs.gitcode_owner }}
        gitcode_repo: ${{ inputs.gitcode_repo }}
        gitcode_token: ${{ inputs.gitcode_token }}
        gitcode_tag_name: ${{ inputs.gitcode_tag_name }}
        gitcode_release_name: ${{ inputs.gitcode_release_name }}
        gitcode_release_body: ${{ inputs.gitcode_release_body }}
        gitcode_target_commitish: ${{ inputs.gitcode_target_commitish }}
        gitcode_files: ${{ inputs.gitcode_files }}
        gitcode_file_name: ${{ inputs.gitcode_file_name }}
        gitcode_file_path: ${{ inputs.gitcode_file_path }}
        gitcode_release_id: ${{ inputs.gitcode_release_id }}
        gitcode_upload_retry_times: ${{ inputs.gitcode_upload_retry_times }}
        gitcode_delete_asset: ${{ inputs.gitcode_delete_asset }}
        gitcode_delete_assets: ${{ inputs.gitcode_delete_assets }}
        gitcode_old_asset_name: ${{ inputs.gitcode_old_asset_name }}
        gitcode_new_file_path: ${{ inputs.gitcode_new_file_path }}
      run: |
        pip install -r "${{ github.action_path }}/requirements.txt"
        python "${{ github.action_path }}/gitcode_release.py"

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: "square"
  color: "blue"
